[project]
name = "projet-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pymodbus>=3.11.2",
]

[tool.uv.workspace]
members = [
    "matplotlib",
    "sklearn",
    "numpy",
    "scikit-learn",
]
